#
# This file is part of the agenda-display project.
#
# (c) Nils Bohrs
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

services:
  server:
    image: "node:alpine"
    restart: always
    env_file:
      - .env
    user: "node"
    working_dir: /home/node/app
    volumes:
      - $PWD:/home/node/app
    ports:
      - "3000:3000"
      - "24678:24678"
    depends_on:
      - redis
    links:
      - redis
    command: "npm run dev"
    networks:
      - agenda-display-network

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - $PWD/db:/data
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - "REDIS_ARGS=--save 120 1 --appendonly yes"
    networks:
      - agenda-display-network

networks:
  agenda-display-network:
    driver: bridge
